server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    #serviceUrl:
    #  defaultZone: http://localhost:8200/eureka/,http://localhost:8300/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
