server:
  port: 9003
  servlet:
    context-path: /
spring:
  application:
    name: wxmp-front
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0  #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大
      rate:
  cloud:
    config:
      username: zhaohg
      password: 123456
      fail-fast: true                 #快速失败
      retry:
        initial-interval: 1100        #下一次重试间隔时间的乘数，比如开始1000，下一次就是1000*1.1=1100
        multiplier: 1.1D              #首次重试间隔时间，默认1000毫秒
        max-interval: 2000            #最大重试时间，默认2000
        max-attempts: 3               #最大重试次数，默认6次

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wxmp?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: mysql
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 500
      min-idle: 500
      max-wait: 5000

  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    timeout: 3000
mybatis:
  type-aliases-package: com.wxmp.front.entity

#jwt:
#  header: Authorization
#restTemplate:
#  url: http://192.168.0.71:7080
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    # 默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 15
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 注册是否显示IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

    metadata-map:
      username: zhangsan
      addr: myAddr
    health-check-url-path: ${server.servlet.context-path}/health
    status-page-url-path: ${server.servlet.context-path}/swagger-ui.html

