server:
  port: 8500
  servlet:
    context-path: /
spring:
  application:
    name: wxmp-oauth-authorization
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0  #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大
      rate:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: mysql
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 500
      min-idle: 500
      max-wait: 5000
  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8


mybatis:
  type-aliases-package: com.wxmp.oauth.entity
logging:
  #  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        web: debug


eureka:
  client:
    enabled: true
    # 开启健康检查（依赖spring-boot-starter-actuator）
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    # 默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 15
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 注册是否显示IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

    metadata-map:
      username: zhangsan
      addr: myAddr
    health-check-url-path: ${server.servlet.context-path}/health
    status-page-url-path: ${server.servlet.context-path}/swagger-ui.html

###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation.:
          thread:
            timeoutInMilliseconds: 60000

#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1