server:
  port: 9411
  context-path: /
spring:
  application:
    name: wxmp-zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:${server.port}
    # 使用http的方式收集链路追踪信息，默认是使用rabbitMQ，这样在使用了spring cloud Bus之后链路追踪就不会失效了
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    metadata-map:
      username: zhangsan
      addr: myAddr
    health-check-url-path: ${server.servlet.context-path}/health
    status-page-url-path: ${server.servlet.context-path}
